#!/bin/sh

f=/tmp/kernel-power-msg
cat > $f <<EOF
This program will remove the enhanced power-user Linux kernel
and restore the original Nokia kernel.
The settings will be kept but will have no effect.

For the deinstallation please make sure that you are connected to
the Internet and that Application Manager is not running.

If you want keep the enhanced kernel, cancel the installation now
by tapping the blurred area above this dialog.
Otherwise confirm the dialog to proceed with the deinstallation.

After the installation, you need to shutdown your device and
boot it again to activate the original Nokia kernel.
EOF
maemo-confirm-text "Kernel-Power Flasher" $f
res=$?
rm -f $f
dbusmsg="run-standalone.sh dbus-send --type=method_call --dest=org.freedesktop.Notifications /org/freedesktop/Notifications org.freedesktop.Notifications.SystemNoteInfoprint"

if test ! "$res" = 0; then
    $dbusmsg string:"User has cancelled the deinstallation. No changes were made."
    exit 1
fi

if pgrep -f /usr/bin/hildon-application-manager > /dev/null; then
    $dbusmsg string:"Error: Application Manager is running. Please close it before deinstallation."
    exit 1
fi

$dbusmsg string:"Please wait while deinstalling enhanced kernel..."

if apt-get install --reinstall -y kernel kernel-flasher | grep "cannot be downloaded"; then
    $dbusmsg string:"Error during deinstallation. Could not install Nokia kernel."
    exit 1
fi
if ! apt-get remove -y kernel-power kernel-power-modules; then
    $dbusmsg string:"Warning: Could not remove enhanced kernel."
else
    $dbusmsg string:"Kernel sucessfully deinstalled. Nokia kernel was restored."
fi

