#!/bin/sh
tmp=/tmp/kernel-power-uninstall
cat > $tmp <<EOF
This program will restore original Nokia kernel
and uninstall package "Linux kernel for power user".
Warning: This method is currently experimental and
could lead to a bricked device. For a safe but manual
method please visit http://wiki.maemo.org/Kernel_Power

This program only uninstall "Linux kernel for power user".
Other packages can be uninstalled in Application Manager.

Before uninstalling please make sure that you are connected to
the Internet and that Application Manager is not running.

If you want keep the Linux kernel for power user installed,
cancel this by tapping the blurred area above this dialog.
Otherwise confirm the dialog to revert back Nokia kernel.

After the uninstallation, you need to unplug the USB cable,
completely shutdown your device, and start it again.
EOF
maemo-confirm-text "Linux kernel for power user" $tmp
res=$?
rm -f $tmp
dbus="run-standalone.sh dbus-send --type=method_call --dest=org.freedesktop.Notifications /org/freedesktop/Notifications"
dbusmsg () { $dbus org.freedesktop.Notifications.SystemNoteInfoprint string:"$1"; }
dbusbox () { $dbus org.freedesktop.Notifications.SystemNoteDialog string:"$1" uint32:0 string:OK; }

if test "$res" != 0; then
    dbusmsg "User has cancelled uninstallation of Linux kernel for power user. No changes were made."
    exit 1
fi

if pgrep -f /usr/bin/hildon-application-manager > /dev/null; then
    dbusbox "Error: Application Manager is running. Please close it before uninstallation."
    exit 1
fi
if pgrep -f apt-worker > /dev/null || pgrep -f apt-get; then
    dbusbox "Error: apt is running. Please wait and try again later."
    exit 1
fi

dbusmsg "Please wait while Nokia kernel will be restored..."

apt-get install --reinstall -y kernel kernel-flasher > $tmp
ok=$?
cat $tmp
if grep -qE "(Could not resolve host|cannot be downloaded)" $tmp; then
    dbusbox "Error during uninstallation: Could not download Nokia kernel. Please make sure the internet connection is working."
    rm $tmp
    exit 1
fi
if test $ok = 0 && grep -q "Image flashed successfully" $tmp; then :
else
    dbusbox "Error during uninstallation: Could not install Nokia kernel."
    rm $tmp
    exit 1
fi
dbusmsg "Nokia kernel was restored. Removing package \"Linux kernel for power user\"..."
apt-get remove --auto-remove -y kernel-power-flasher > $tmp
ok=$?
cat $tmp
if test $ok = 0; then
    dbusbox "Linux kernel for power user was sucessfully uninstalled. Nokia kernel was restored."
else
    dbusbox "Warning: Nokia kernel was restored but removing package \"Linux kernel for power user\" failed."
fi
rm $tmp
exit $ok
