#!/bin/sh

f="$1"
test $# -eq 0 && f=/etc/default/kernel-power
test -f "$f" || exit 1
source "$f"
test -n "$UP_THRESHOLD" && echo $UP_THRESHOLD > /sys/devices/system/cpu/cpu0/cpufreq/ondemand/up_threshold
test -n "$SAMPLING_RATE" && echo $SAMPLING_RATE > /sys/devices/system/cpu/cpu0/cpufreq/ondemand/sampling_rate
test -n "$MIN_FREQ" && echo $MIN_FREQ > /sys/devices/system/cpu/cpu0/cpufreq/scaling_min_freq
test -n "$MAX_FREQ" && echo $MAX_FREQ > /sys/devices/system/cpu/cpu0/cpufreq/scaling_max_freq
test -n "$VDD1_OPPS_VSEL" && echo $VDD1_OPPS_VSEL > /sys/power/vdd1_opps_vsel
test -n "$DSP_OPPS_RATE" && echo $DSP_OPPS_RATE > /sys/power/dsp_opps_rate
test -n "$SMARTREFLEX_VDD1" && echo $SMARTREFLEX_VDD1 > /sys/power/sr_vdd1_autocomp
test -n "$SMARTREFLEX_VDD2" && echo $SMARTREFLEX_VDD2 > /sys/power/sr_vdd2_autocomp
exit 0
