#!/bin/sh

set -e

if grep -q "# KERNEL-POWER-HOOK" /etc/default/mount-opts; then
    grep -v "# KERNEL-POWER-HOOK" /etc/default/mount-opts > /etc/default/mount-opts.tmp
    mv /etc/default/mount-opts.tmp /etc/default/mount-opts
fi

case "$1" in
purge)
    rm -f /etc/default/kernel-power /etc/default/kernel-boot
    rm -rf /etc/kernel-power
    ;;
esac

#DEBHELPER#

exit 0
