#!/bin/sh

set -e

# remove old files
rm -f /etc/event.d/kernel
rm -f /etc/event.d/kernel-maemo
rm -f /etc/lastboot
rm -f /etc/lastreboot
rm -f /etc/kernel-power/pre-mount
rm -f /etc/default/kernel-boot

# remove old hook
if grep -q '# KERNEL-POWER-HOOK' /etc/default/mount-opts; then
    sed '/# KERNEL-POWER-HOOK/d' -i /etc/default/mount-opts
fi

update-sudoers

#DEBHELPER#

exit 0
